import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
	<html lang="en">
		<body
			className={`${inter.className} bg-default-background text-default-text`}
		>
			<main className="container mx-auto px-10">{children}</main>
		</body>
	</html>
);

export default RootLayout;
