import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const RootLayout = () => (
	<html lang="en">
		<body className={inter.className}>
			<h1>Hello</h1>
		</body>
	</html>
);

export default RootLayout;
