import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
	<html lang="en">
		<body className={inter.className}>
			<nav className="bg-slate-200">
				<ul className="container mx-auto flex gap-x-6 px-10 py-4">
					<li>
						<Link href="/camp">Future Camps</Link>
					</li>
					<li>
						<Link href="/about">Camp news</Link>
					</li>
				</ul>
			</nav>

			<main className="container mx-auto px-10">{children}</main>
		</body>
	</html>
);

export default RootLayout;
